### ISSUE TITLE
Add open graph metadata

### ISSUE THREAD

**Issue by ckcollab** [codalab/chahub#106]

**Comment by ckcollab** [comment]
Added the following description:

> "Chahub is a resource aggregator for machine learning researchers and students. We track many machine learning competitions, datasets, and competitors."

I think that sounds good? Pulled it from our Wiki docs.

**Comment by ieee8023** [comment]
The image still does not show up. The error from the facebook sharing debugger is:

> Provided og:image URL, https://chahub.org/static/img/chahub_logo_with_background.b0dcfbf66bd8.png was not valid because it did not meet the minimum size constraint of 200px by 200px.

**Comment by ieee8023** [comment]
How about this image?

High res:
<img width="907" alt="image-sharing-highres" src="https://user-images.githubusercontent.com/446367/46630604-b0bfa680-cb12-11e8-9f42-82fdf841a9a9.png">

Low res (Still high enough):
<img width="358" alt="image-sharing-lowres" src="https://user-images.githubusercontent.com/446367/46630611-b5845a80-cb12-11e8-8805-90ff8d3bb932.png">

**Comment by ckcollab** [comment]
Fixed (I believe!), thanks so much for getting a high res version! Really appreciate it.

**Comment by ieee8023** [comment]
It works well on facebook!

<img width="503" alt="screen shot 2018-10-08 at 4 09 20 pm" src="https://user-images.githubusercontent.com/446367/46631149-938bd780-cb14-11e8-80bd-e7ec738b3dcd.png">

**Comment by ckcollab** [comment]
Please, if you have any more advice/suggestions let us know -- looks much better than it did, I am sure!
