### ISSUE TITLE
Research + Spec out what Chahub profiles will be like (see Kaggle and Codalab currently for examples)

### ISSUE THREAD

**Issue by ckcollab** [codalab/chahub#141]
Some example details we may want to display:
- How many submissions recently? When was last submission? Or maybe just a list of submissions?
- What is their organization, bio, etc. normal details
- Hall of Fame details?

**Comment by BrendanMyers88** [comment]
Progress on the Account Tab. 

<img width="1440" alt="screen shot 2019-03-01 at 4 22 26 pm" src="https://user-images.githubusercontent.com/19380562/53673786-834cd400-3c3e-11e9-870f-67f25bc14b39.png">
