### ISSUE TITLE
Auth Review

### ISSUE THREAD

**Issue by jimmykodes** [codalab/chahub#166]
Chahub: https://codalabchahub-pr-165.herokuapp.com/
Competition v2: https://competitions-v2-staging-pr-226.herokuapp.com/

Login on ChaHub
- [x] go to the [ChaHub site](https://codalabchahub-pr-165.herokuapp.com/) and click the login button
- [x] click on "Sign Up" and fill out the form to create a new account
- [x] you should receive an email from noreply@ChaHub.org asking you to verify your email address
- [x] on this same page login page, you can also create an account on chahub through oauth with github

ChaHub Account
- [x] once logged in, click on the button in the upper right corner, in the dropdown, select "My Profile"
- [x] in the header, click on account (next to details)
- [x] this should take you to a table of email addresses. the one you used to sign up should be listed as your primary email address
- [x] if you clicked the verification link in the email, there should also be a checkbox in the verified column
- [x] otherwise, there should be a button w/ a paper airplane that will re-send the verification email
- [x] clicking the button "Add email address" should open up a modal where you can input a new email address
- [x] doing so will send another verification email, and add an unverified email address to the table
- [x] this table should have the options to delete the email address or resend the verification email
- [x] once this email is verified, the action buttons should no be "delete" and "make primary" (there are tooltips on button hover to make this clear)
- [x] Here the user can also link their account w/ a github account (if they chose not to auth w/ github at account creation)
- [x] There is also the ability to merge accounts (discussed below)
- [x] finally, you can delete your account, which will delete the user, and any github info associated w/ that user

ChaHub Profiles
- [x] go to the [v2 site](https://competitions-v2-staging-pr-226.herokuapp.com/) and create a new user here using the "Sign Up" button in the upper right
- [x] this new user will be sent to ChaHub as a profile
- [x] if you used the same email address to sign up on both ChaHub and Codalab, and the email on ChaHub has been verified, there should now be a profile listed in your profile details page
- [x] if you used a different email address, go to ChaHub and add the email address to your account. once that email address has been verified, the profile will be linked to your user
- [x] to comply with GDPR, you may delete your profile from v2 using the delete button in the profile table. this scrubs all identifiable information from the profile, but keeps the producer:remote_id pair. This way we still get user statistics, but all identifiable information has been scrubbed and will not be sent by the producer

Merge Accounts
- [x] Profiles are linked to user accounts via verified email addresses, so any producer profiles can be connected to a user by added the email address of their profile on the producer to their verified email addresses on their account
- [x] If a user has multiple _ChaHub_ accounts, this is where the merge accounts button comes in.
- [x] clicking this button takes you to a form where you specify a master account (the one being merged _in to_) and a secondary account(the one being merged)
- [x] clicking submit creates a merge request and sends an email to the secondary account for verification
- [x] if the verification link in the email is followed, all the email addresses, profiles, and github information from the secondary account will be added to the master account

Auth w/ chahub
- [x] go to the [v2 site](https://competitions-v2-staging-pr-226.herokuapp.com/) and click on login
- [ ] click "sign in with ChaHub". this will take you to chahub where you can log in as an existing chahub user, which will then create a v2 user from this information
- [x] the button "Create a chahub account" will also take you to chahub, but in a new window and to the user creation form, filling this out will create a chahub user, you can then go back to the chahub window and click "Sign in with ChaHub" to link v2 with your newly created ChaHub user.

**Comment by madclam** [comment]
First screen empty, would be good to populate it.
<img width="1254" alt="Screen Shot 2019-09-20 at 6 22 19 PM" src="https://user-images.githubusercontent.com/7594063/65342944-1ac24600-dbd4-11e9-9f0a-f3a3094834be.png">
Tried to create an account, got error:
<img width="430" alt="Screen Shot 2019-09-20 at 6 24 51 PM" src="https://user-images.githubusercontent.com/7594063/65343008-4b09e480-dbd4-11e9-8739-6637050290a6.png">
Tried to login with GitHub,  got error:
<img width="612" alt="Screen Shot 2019-09-20 at 6 25 02 PM" src="https://user-images.githubusercontent.com/7594063/65343020-565d1000-dbd4-11e9-87c9-40670f2d9f52.png">

**Comment by madclam** [comment]
Part II: Codalab v2
[+] Could create an account.
[-] Did not receive any confirmation email.
[-] Did not sync with ChaHub.

**Comment by jimmykodes** [comment]
@madclam There were issues with some heroku environment variables. They are fixed now and this  _should_ all be working now.

**Comment by jimmykodes** [comment]
- [ ] Fix ownership of Chahub Github app

**Comment by madclam** [comment]
CHAHUB testing with Jimmy:
[-] Log in with Github. Authorization initiated but 500 error happened when confirming password.

**Comment by jimmykodes** [comment]
- [ ] email collision on sign up with github (we are already handling username collisions)

**Comment by jimmykodes** [comment]
- need to authorize master email address, too on account merge
- fix typo in authorize email address email.

**Comment by jimmykodes** [comment]
- merges should be done w/ primary account email addresses

**Comment by jimmykodes** [comment]
- warning message on profile deletion "Are you sure you want to delete this _PROFILE_" not _account_

**Comment by madclam** [comment]
Part III: Login on V2 using "login with ChaHub"
<img width="583" alt="Screen Shot 2019-09-20 at 8 08 02 PM" src="https://user-images.githubusercontent.com/7594063/65348910-827f8d80-dbe2-11e9-8e78-262bb39ba85f.png">
