### ISSUE TITLE
With default search results, the most recently added should appear on top

### ISSUE THREAD

**Issue by ckcollab** [codalab/chahub#84]
Isabelle: _"It would be nice to see https://chahub.org/?date_flags=active&sorting=prize by default when we get to the ChaHub page (NOT the link pointing from LRI though, for this one, let’s use https://chahub.org/?sorting=participant_count&producer=1)"_

**Comment by Tthomas63** [comment]
It looks like we added default sorting based off of the `start` field, but wouldn't we want the un-documented `created_when` field on the actual model in this case?

**Comment by ckcollab** [comment]
Using sort on `-start` seems fine?
